let items=[],active='All';
const $=id=>document.getElementById(id);
const categories=['All','Upper Extremity','Lower Extremity','Spine','Chest/Abdomen','Skull/Facial'];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderNav(){ $('categoryContainer').innerHTML=categories.map(c=>`<button class="${c===active?'active':''}" data-cat="${c}">${c==='All'?'ทั้งหมด':c}</button>`).join('');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{active=b.dataset.cat;renderNav();filter()}) }
function filter(){const q=$('searchInput').value.trim().toLowerCase();const found=items.filter(x=>(active==='All'||x.category===active)&&(!q||[x.name_en,x.name_th,x.category,x.clinical_indication,...(x.aliases||[])].join(' ').toLowerCase().includes(q)));$('status').textContent=found.length?`${found.length} ท่า`:'ไม่พบข้อมูล';$('positionsGrid').innerHTML=found.length?found.map(x=>`<article class="card" tabindex="0" data-id="${esc(x.id)}"><div class="card-top"><span class="tag">${esc(x.category)}</span><span class="arrow">↗</span></div><h3>${esc(x.name_en)}</h3><p class="thai">${esc(x.name_th)}</p><p>${esc(x.clinical_indication)}</p><footer><span class="status-dot"></span>${x.model_url?'เปิด 3D และพารามิเตอร์':'ดูพารามิเตอร์และ checklist'} <b>→</b></footer></article>`).join(''):`<div class="empty"><div>⌕</div><h3>ยังไม่พบรายการ</h3><p>ลองค้นหาด้วยชื่อภาษาอังกฤษหรือเลือกหมวดหมู่อื่น</p></div>`;document.querySelectorAll('.card').forEach(c=>{c.onclick=()=>open(items.find(x=>x.id===c.dataset.id));c.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')open(items.find(x=>x.id===c.dataset.id))}})}
let currentItem=null;let fallbackUsed=false;
function setView(mode){if(!currentItem)return;const hasImage=Boolean(currentItem.image_url)&&!$('positionImage').classList.contains('image-failed'),hasModel=Boolean(currentItem.model_url)||fallbackUsed;const image=$('positionImage'),viewer=$('modelViewer'),empty=$('viewerEmpty');$('imageTab').classList.toggle('active',mode==='image');$('modelTab').classList.toggle('active',mode==='model');$('modelTab').textContent=hasModel?'◇ โมเดล 3D':'◇ โมเดล 3D · รอไฟล์';image.classList.toggle('hidden',mode!=='image'||!hasImage);viewer.classList.toggle('hidden',mode!=='model'||!hasModel);empty.classList.toggle('hidden',(mode==='image'&&hasImage)||(mode==='model'&&hasModel));if(mode==='model'&&!hasModel){$('modelBadge').textContent='MODEL PENDING';$('viewerEmpty').querySelector('strong').textContent='ยังไม่มีโมเดล 3D ของท่านนี้';$('viewerEmpty').querySelector('span').textContent='เพิ่มไฟล์ GLB เฉพาะท่านี้แล้วจะหมุนดูได้จริง'}if(mode==='image'&&hasImage){$('modelBadge').textContent='IMAGE GUIDE';$('viewerEmpty').querySelector('strong').textContent='ยังไม่มีภาพการจัดท่า';$('viewerEmpty').querySelector('span').textContent='เพิ่มภาพต้นฉบับหรือภาพที่สร้างใหม่ได้ภายหลัง'}}
function open(x){currentItem=x;fallbackUsed=false;$('modalTitle').textContent=x.name_en;$('modalCategory').textContent=`${x.category} • ${x.name_th}`;const viewer=$('modelViewer'),image=$('positionImage');viewer.removeAttribute('src');image.removeAttribute('src');image.classList.remove('image-failed');image.onerror=()=>{image.classList.add('image-failed');image.removeAttribute('src');$('sourceCredit').textContent='ยังไม่มีภาพจัดท่าที่โหลดได้';$('modelBadge').textContent='IMAGE UNAVAILABLE';setView('image')};image.onload=()=>{image.classList.remove('image-failed');setView('image')};$('sourceCredit').classList.toggle('hidden',!x.image_credit);$('sourceCredit').textContent=x.image_credit||'';$('modelBadge').textContent=x.model_url?'3D READY':x.image_url?'IMAGE GUIDE':'INFO MODE';if(x.model_url){viewer.src=x.model_url;viewer.onerror=()=>{$('modelBadge').textContent='MODEL ERROR';setView('model')}}if(x.image_url){image.src=x.image_url;image.alt=`ภาพการจัดท่า ${x.name_en}`}const p=x.parameters||{};$('details').innerHTML=`<div class="detail highlight"><strong>SID / IR</strong><span>${esc(p.sid)}<br>${esc(p.ir_size)}</span></div><div class="detail highlight"><strong>TUBE / GRID</strong><span>${esc(p.tube_angle)}<br>${esc(p.grid)}</span></div><div class="detail highlight"><strong>EXPOSURE</strong><span>${esc(p.kvp_range)}<br>${esc(p.mas_range)}</span></div><div class="detail wide highlight"><strong>CENTRAL RAY · จุดสำคัญ</strong><span>${esc(p.central_ray)}</span></div><div class="detail wide"><strong>การจัดท่าผู้ป่วย</strong><span>${esc(x.patient_position)}</span></div><div class="detail wide"><strong>เกณฑ์ภาพที่ดี · เช็กก่อนกดถ่าย</strong><ul>${(x.image_criteria||[]).map(i=>`<li>${esc(i)}</li>`).join('')}</ul></div><div class="detail wide tip"><strong>PRO TIP · จุดที่ควรปรับ/ระวัง</strong><span>${esc(x.pro_tips)}</span></div>`;$('detailModal').classList.remove('hidden');document.body.classList.add('modal-open');setView(x.image_url?'image':'model')}
async function init(){try{const res=await fetch('data/positions.json');if(!res.ok)throw new Error('positions.json');items=await res.json();renderNav();filter()}catch(e){$('status').textContent='โหลดข้อมูลไม่สำเร็จ กรุณาตรวจสอบ data/positions.json'}}
$('searchInput').oninput=filter;
$('closeModalBtn').onclick=()=>$('detailModal').classList.add('hidden');
$('closeModalBtn').onclick=closeModal;
function closeModal(){$('detailModal').classList.add('hidden');document.body.classList.remove('modal-open');$('modelViewer').removeAttribute('src');$('positionImage').removeAttribute('src')}
$('themeBtn').onclick=()=>{document.body.classList.toggle('light');$('themeBtn').textContent=document.body.classList.contains('light')?'☾':'☼'};
$('imageTab').onclick=()=>setView('image');$('modelTab').onclick=()=>setView('model');
document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('searchInput').focus()}if(e.key==='Escape')closeModal()});
if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js?build=10').catch(console.warn);
$('detailModal').onclick=e=>{if(e.target.id==='detailModal')closeModal()};init();


