let items=[],active='All';
const $=id=>document.getElementById(id);
const categories=['All','Upper Extremity','Lower Extremity','Spine','Chest/Abdomen','Skull'];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderNav(){ $('categoryContainer').innerHTML=categories.map(c=>`<button class="${c===active?'active':''}" data-cat="${c}">${c==='All'?'ทั้งหมด':c}</button>`).join('');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{active=b.dataset.cat;renderNav();filter()}) }
function filter(){const q=$('searchInput').value.trim().toLowerCase();const found=items.filter(x=>(active==='All'||x.category===active)&&(!q||[x.name_en,x.name_th,x.category,x.clinical_indication,...(x.aliases||[])].join(' ').toLowerCase().includes(q)));$('status').textContent=found.length?`${found.length} รายการ`:'ไม่พบข้อมูลท่าตรวจที่ค้นหา';$('positionsGrid').innerHTML=found.map(x=>`<article class="card" data-id="${esc(x.id)}"><div class="tag">${esc(x.category)}</div><h3>${esc(x.name_en)}</h3><p>${esc(x.name_th)}</p><p>${esc(x.clinical_indication)}</p><footer>เปิด 3D และพารามิเตอร์ →</footer></article>`).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>open(items.find(x=>x.id===c.dataset.id)))}
function open(x){$('modalTitle').textContent=x.name_en;$('modalCategory').textContent=`${x.category} • ${x.name_th}`;$('modelViewer').src=x.model_url||'';const p=x.parameters||{};$('details').innerHTML=`<div class="detail"><strong>SID / IR</strong><span>${esc(p.sid)}<br>${esc(p.ir_size)}</span></div><div class="detail"><strong>Tube angle / Grid</strong><span>${esc(p.tube_angle)}<br>${esc(p.grid)}</span></div><div class="detail wide"><strong>Central ray</strong><span>${esc(p.central_ray)}</span></div><div class="detail wide"><strong>การจัดท่าผู้ป่วย</strong><span>${esc(x.patient_position)}</span></div><div class="detail wide"><strong>เกณฑ์ภาพที่ดี</strong><ul>${(x.image_criteria||[]).map(i=>`<li>${esc(i)}</li>`).join('')}</ul></div><div class="detail wide tip"><strong>Pro tip</strong><span>${esc(x.pro_tips)}</span></div>`;$('detailModal').classList.remove('hidden')}
async function init(){try{items=await (await fetch('data/positions.json')).json();renderNav();filter()}catch(e){$('status').textContent='โหลดข้อมูลไม่สำเร็จ กรุณาตรวจสอบ data/positions.json'}}
$('searchInput').oninput=filter;
$('closeModalBtn').onclick=()=>$('detailModal').classList.add('hidden');
if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(console.warn);
$('detailModal').onclick=e=>{if(e.target.id==='detailModal')e.currentTarget.classList.add('hidden')};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('detailModal').classList.add('hidden')});init();
