const STORAGE_API='https://script.google.com/macros/s/AKfycbwwTpE3bs6IvaYfRV-qbiqpeSAXX5eyQX__XGzgojUs6iwAN50mxCIEzdsMMn5ciObaxQ/exec';
const DRIVE_FOLDER_ID='1C9q5Pj95wiE4unuN8MkYCtzV78lrfVQa', SHEET_ID='12Ofd9C2RMEQuQxLaXz_St1hztb7qo0G79zt7bdc5wh4';
const subjectsKey='orbit-subjects', recordingsKey='orbit-recordings';
let subjects=JSON.parse(localStorage.getItem(subjectsKey)||'[]'), recordings=JSON.parse(localStorage.getItem(recordingsKey)||'[]');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(subjectsKey,JSON.stringify(subjects));localStorage.setItem(recordingsKey,JSON.stringify(recordings));}
function subjectHTML(s){return `<div class="subject" data-id="${s.id}"><div class="subject-icon" style="background:${s.color};color:${s.text}">${s.icon}</div><b>${s.name}</b><small>${s.lectureCount||0} เลคเชอร์</small><button class="subject-delete" data-delete-subject="${s.id}" title="ลบวิชา">×</button><span class="arrow">→</span></div>`}
function renderSubjects(){ $('#subject-grid').innerHTML=subjects.slice(0,4).map(subjectHTML).join('')||'<div class="empty-state">ยังไม่มีวิชา <a href="#subjects" data-page="subjects">เพิ่มวิชาแรก →</a></div>'; $('#all-subjects').innerHTML=subjects.map(subjectHTML).join('')||'<div class="empty-state">ยังไม่มีวิชา กด “เพิ่มวิชา” เพื่อเริ่มต้น</div>'; $('.muted').textContent=`${subjects.length} วิชา`;}
function renderRecordings(){const html=recordings.map(r=>`<div class="record-row"><div class="play">▶</div><div><b>${r.title}</b><small>${r.subject||'ไม่ระบุวิชา'} · ${new Date(r.startedAt).toLocaleString('th-TH')}</small></div><span class="duration">${r.duration}</span><span class="status done">เสร็จสิ้น ${new Date(r.completedAt).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}</span><button class="more" data-delete-recording="${r.id}">×</button></div>`).join(''); $('.recent-head + .recording-list').innerHTML=html||'<div class="empty-state">ยังไม่มีเลคเชอร์ที่บันทึก</div>'; $('#library-list').innerHTML=html||'<div class="empty-state">คลังไฟล์ยังว่าง</div>';}
const pages=$$('.page'); function showPage(id){pages.forEach(p=>p.classList.toggle('active-page',p.id===id));$$('[data-page]').forEach(a=>a.classList.toggle('active',a.dataset.page===id));const titles={dashboard:'สวัสดี, Phumshop 👋',record:'อัดเลคเชอร์',library:'คลังไฟล์',exam:'หมุดเตรียมสอบ',subjects:'วิชาของฉัน',profile:'โปรไฟล์ของฉัน',settings:'ตั้งค่า'};$('#page-title').innerHTML=titles[id]||titles.dashboard;location.hash=id;renderSubjects();renderRecordings();if(id==='profile')renderProfile();}
function renderProfile(){const name=localStorage.getItem('orbit-name')||'Phumshop';$('#profile-name').value=name;$('#profile-display-name').textContent=name;$('#profile-avatar-large').textContent=name[0]?.toUpperCase()||'P';$('#profile-lecture-count').textContent=recordings.length;$('#profile-subject-count').textContent=subjects.length;}
document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page){e.preventDefault();showPage(page.dataset.page)}const del=e.target.closest('[data-delete-subject]');if(del&&confirm('ลบวิชานี้หรือไม่?')){subjects=subjects.filter(s=>s.id!==del.dataset.deleteSubject);save();renderSubjects()}const dr=e.target.closest('[data-delete-recording]');if(dr&&confirm('ลบรายการนี้หรือไม่?')){recordings=recordings.filter(r=>r.id!==dr.dataset.deleteRecording);save();renderRecordings()}if(e.target.closest('#add-subject')){const name=prompt('ชื่อวิชา');if(name?.trim()){const colors=[['#e0e7ff','#4f46e5'],['#dcfce7','#16a34a'],['#fef3c7','#d97706'],['#fce7f3','#db2777']];const c=colors[subjects.length%colors.length];subjects.push({id:crypto.randomUUID(),name:name.trim(),icon:'📚',color:c[0],text:c[1],lectureCount:0});save();renderSubjects()}}if(e.target.closest('#profile-button')||e.target.closest('#profile-button-top'))showPage('profile');if(e.target.closest('#notification-button'))alert(recordings.length?'มีรายการอัดเสียงล่าสุด '+recordings.length+' รายการ':'ยังไม่มีการแจ้งเตือน');if(e.target.closest('#search-button')){const q=prompt('ค้นหาเลคเชอร์หรือวิชา');if(q)showPage(recordings.some(r=>r.title.includes(q))?'library':'subjects')}if(e.target.closest('#profile-save')){const name=$('#profile-name').value.trim()||'Phumshop';localStorage.setItem('orbit-name',name);$('#profile-display-name').textContent=name;$('#profile-avatar-large').textContent=name[0].toUpperCase();alert('บันทึกโปรไฟล์แล้ว')}});
let media=null,chunks=[],seconds=0,interval,chunkNo=0,startedAt=null,currentSubject='';const timer=$('#timer'),status=$('#rec-status'),orb=$('#rec-orb'),start=$('#record-btn'),stop=$('#stop-btn');const fmt=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');const b64=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(blob)});
async function uploadChunk(blob,index,total){if(!blob?.size)return;status.textContent=`กำลังอัปโหลดช่วงที่ ${index+1}...`;const payload={action:'saveChunk',recordingId:sessionStorage.getItem('orbit-recording-id')||crypto.randomUUID(),chunkIndex:index,totalChunks:total,fileName:`orbit-lecture-${Date.now()}-${index}.webm`,mimeType:'audio/webm',audioBase64:await b64(blob),durationSeconds:seconds,driveFolderId:DRIVE_FOLDER_ID,sheetId:SHEET_ID,title:currentSubject||'OrbitNotes lecture'};sessionStorage.setItem('orbit-recording-id',payload.recordingId);const res=await fetch(STORAGE_API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});const out=await res.json();if(!out.ok)throw new Error(out.error||'Upload failed');status.textContent=`อัปโหลดแล้วช่วงที่ ${index+1}`;return out;}
start.onclick=async()=>{try{currentSubject=prompt('วิชานี้คือวิชาอะไร?')||'ไม่ระบุวิชา';startedAt=new Date();const stream=await navigator.mediaDevices.getUserMedia({audio:true});media=new MediaRecorder(stream,{mimeType:'audio/webm;codecs=opus'});chunks=[];chunkNo=0;sessionStorage.removeItem('orbit-recording-id');media.ondataavailable=async e=>{if(e.data.size)chunks.push(e.data);if(chunks.length>=5){try{await uploadChunk(new Blob(chunks.splice(0,5),{type:'audio/webm'}),chunkNo++,Math.ceil((seconds||1)/300));}catch(err){status.textContent='อัปโหลดไม่สำเร็จ กรุณาลองใหม่';console.error(err);}}};media.onstop=async()=>{try{if(chunks.length)await uploadChunk(new Blob(chunks,{type:'audio/webm'}),chunkNo++,chunkNo+1);const rec={id:crypto.randomUUID(),title:currentSubject,subject:currentSubject,duration:fmt(seconds),startedAt:startedAt.toISOString(),completedAt:new Date().toISOString()};recordings.unshift(rec);save();renderRecordings();status.textContent=`เสร็จสิ้นเวลา ${new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}`;}catch(err){status.textContent='บันทึกเสร็จ แต่ส่งไฟล์ไม่สำเร็จ';}};media.start(60000);seconds=0;timer.textContent='00:00';interval=setInterval(()=>{seconds++;timer.textContent=fmt(seconds)},1000);orb.classList.add('recording');status.textContent='กำลังบันทึกเสียง...';start.disabled=true;stop.disabled=false;start.textContent='● กำลังอัดเสียง';}catch(e){status.textContent='ไม่สามารถเข้าถึงไมโครโฟนได้';}};
stop.onclick=()=>{if(media){media.stop();media.stream.getTracks().forEach(t=>t.stop());}clearInterval(interval);orb.classList.remove('recording');start.disabled=false;stop.disabled=true;start.textContent='● เริ่มอัดเสียง';};
renderSubjects();renderRecordings();showPage(location.hash.slice(1)||'dashboard');
